"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--k_#1w4iwb7ctbukue#p8i(9z26k+$)@(_+hi%bkdfnq^dodk*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'www.buyjoi.com','buyjoi.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'buyjoi',
    'django.contrib.sites',

    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'buyjoi/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


CSRF_TRUSTED_ORIGINS=['https://*.buyjoi.COM']

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'dbsqlite3'),
       
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    "/var/www/static/",
   ]

STATIC_ROOT = '/home/buyjclsn/public_html/'


MEDIA_URL = '/img/'

MEDIA_ROOT = BASE_DIR / 'static'





# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1", "buyjoi.com", "www.buyjoi.com",
]

SITE_ID = 1

LOGIN_URL = 'https://buyjoi.com/login' , 'https://www.buyjoi.com/login' , 'https://127.0.0.1:8000/login'
LOGOUT_URL = 'https://buyjoi.com/logout' , 'https://www.buyjoi.com/logout' , 'https://127.0.0.1:8000/logout'
LOGIN_REDIRECT_URL = "/"




#Logs Logging Configuration

LOGGING ={
	'version':1,
	'logger':{
		'django':{
		'handlers':['file', 'file2', 'file3', 'file4', 'file5',],
		'level':'DEBUG'		
		}	
	},
	
	'handlers':{
		'file':{
			'level':'INFO',
			'class':'logging.FileHandler',
			'filename':'./logs/info.log',
			'formatter':'simpleRe',
		},
        'file2':{
			'level':'DEBUG',
			'class':'logging.FileHandler',
			'filename':'./logs/debug.log',
			'formatter':'simpleRe',
		},
		'file3':{
			'level':'WARNING',
			'class':'logging.FileHandler',
			'filename':'./logs/warning.log',
			'formatter':'simpleRe',
		},
		'file4':{
			'level':'ERROR',
			'class':'logging.FileHandler',
			'filename':'./logs/error.log',
			'formatter':'simpleRe',
		},
		'file5':{
			'level':'CRITICAL',
			'class':'logging.FileHandler',
			'filename':'./logs/critical.log',
			'formatter':'simpleRe',
		}


	},
	'formatters':{
		'simpleRe':{
			'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
		'style':'{',
		}
	}


}