# Generated by Django 4.1.3 on 2023-02-17 12:23

import buyjoi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('round_image', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default 1=trending')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=750)),
                ('meta_description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailtosubscribe', models.CharField(max_length=1150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1150)),
                ('lname', models.CharField(max_length=1150, null=True)),
                ('phone', models.CharField(max_length=1150)),
                ('pincode', models.CharField(max_length=1150)),
                ('flat', models.CharField(max_length=1150)),
                ('area', models.CharField(max_length=1150)),
                ('landmark', models.CharField(max_length=1150)),
                ('city', models.CharField(max_length=1150)),
                ('state', models.CharField(max_length=1150)),
                ('country', models.CharField(max_length=1150)),
                ('addresstype', models.CharField(max_length=1150)),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=1150)),
                ('name', models.CharField(blank=True, max_length=1150)),
                ('product_image1', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('product_image2', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('product_image3', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('small_description', models.TextField(blank=True, max_length=1500)),
                ('quantity', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=12500)),
                ('original_price', models.FloatField(blank=True)),
                ('selling_price', models.FloatField(blank=True)),
                ('rating_number', models.CharField(blank=True, max_length=1150)),
                ('status', models.BooleanField(default=False, help_text='0=default 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default 1=trending')),
                ('homepage', models.BooleanField(default=False, help_text='0=default 1=trending')),
                ('tag', models.CharField(blank=True, max_length=1150)),
                ('meta_title', models.CharField(blank=True, max_length=1150)),
                ('meta_keywords', models.CharField(blank=True, max_length=1750)),
                ('meta_description', models.TextField(blank=True, max_length=12500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1150)),
                ('lname', models.CharField(max_length=1150, null=True)),
                ('phone', models.CharField(max_length=1150)),
                ('pincode', models.CharField(max_length=1150)),
                ('flat', models.CharField(max_length=1150)),
                ('area', models.CharField(max_length=1150)),
                ('landmark', models.CharField(max_length=1150)),
                ('city', models.CharField(max_length=1150)),
                ('state', models.CharField(max_length=1150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.product')),
            ],
        ),
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=1150)),
                ('name', models.CharField(blank=True, max_length=1150)),
                ('product_image1', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('product_image2', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('product_image3', models.ImageField(blank=True, upload_to=buyjoi.models.get_file_path)),
                ('small_description', models.TextField(blank=True, max_length=1500)),
                ('quantity', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=12500)),
                ('original_price', models.FloatField(blank=True)),
                ('selling_price', models.FloatField(blank=True)),
                ('rating_number', models.CharField(blank=True, max_length=1150)),
                ('status', models.BooleanField(default=False, help_text='0=default 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default 1=trending')),
                ('homepage', models.BooleanField(default=False, help_text='0=default 1=trending')),
                ('tag', models.CharField(blank=True, max_length=1150)),
                ('meta_title', models.CharField(blank=True, max_length=1150)),
                ('meta_keywords', models.CharField(blank=True, max_length=1750)),
                ('meta_description', models.TextField(blank=True, max_length=12500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyjoi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
