# Generated by Django 4.1.3 on 2023-02-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyjoi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=1150, null=True)),
                ('personemail', models.CharField(max_length=1150, null=True)),
                ('personmessage', models.TextField(blank=True, max_length=12500)),
            ],
        ),
    ]
