# Generated by Django 4.2.1 on 2023-06-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyjoi', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
