# Generated by Django 4.2.1 on 2023-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyjoi', '0003_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
