# Generated by Django 4.2.1 on 2023-06-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyjoi', '0004_wishlist_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='session_key',
        ),
    ]
